# Use root/example as user/password credentials
version: '3.5'

volumes:
  datadb:

services:
  mongo:
    image: mongo:4.4
    restart: always
    ports:
      - 27017:27017
    volumes:
      - datadb:/data/db
      - ./mongo-scripts/:/docker-entrypoint-initdb.d/
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: admin
      MONGO_INITDB_DATABASE: mowerPlannerDb
  mongo-express:
    image: mongo-express:0.54
    restart: always
    ports:
      - 9000:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: admin