name: "node-build"
description: "Build and test a node app"
inputs:
  test-app:
    description: "Determine whether or not we test the code"
    type: boolean
    required: true
    default: false

runs: 
  using: composite
  steps:
    - run: npm ci
      shell: bash
    - run: npm run build --if-present
      shell: bash
    - run: npm test
      if: ${{ inputs.test-app == 'true' }}
      shell: bash
