name: "node-build"
description: "Build and test a node app"
inputs:
   testApp:
     required: false
     description: "Determine whether or not we test the code"

runs: 
  using: composite
  steps:
    - run: npm ci
      shell: bash
    - run: npm run build --if-present
      shell: bash
    - run: npm test
      if: ${{inputs.testApp == true}}
      shell: bash
