# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Build Mower-Planner application and deploy it to production

on:
  release:
    types: [created]


env:
  APP_NAME: mower-planner
  REGISTRY_LOCALE: europe-west1-docker.pkg.dev
  REGISTRY_PATH: europe-west1-docker.pkg.dev/mower-planner/registry
  GKE_PROJECT: mower-planner
  GKE_ZONE: europe-west1-c
  GKE_CLUSTER: cluster-mower-planner

jobs:
  build-app:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
    - name: Use Node.js 16.x
      uses: actions/setup-node@v3
      with:
        node-version: 16.x
        cache: "npm"
    - name: Build and test app
      uses: ./.github/actions/build-node
      with:
        testApp: true

  build-image:
    runs-on: ubuntu-latest
    needs: build-app
    permissions:
      contents: 'read'
      id-token: 'write'
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
    - name: Get app version from package.json
      id: package-version
      uses: martinbeentjes/npm-get-version-action@master
    - name: 'Authenticate to Google Cloud'
      id: 'auth'
      uses: 'google-github-actions/auth@v0'
      with:
        workload_identity_provider: ${{ secrets.GCLOUD_WORKLOAD_IDENTITY_PROVIDER }}
        service_account: ${{ secrets.GCLOUD_SVC_ACCOUNT }}
    - name: Use Node.js 16.x
      uses: actions/setup-node@v3
      with:
        node-version: 16.x
        cache: "npm"
    - name: Build app
      uses: ./.github/actions/build-node
      with:
        testApp: false
    - name: Build the Docker image and push to Artefact Registry
      env:
        APP_VERSION: ${{ steps.package-version.outputs.current-version }}
      run: |
        gcloud auth configure-docker $REGISTRY_LOCALE
        docker build . --tag $APP_NAME:$APP_VERSION
        docker tag $APP_NAME:$APP_VERSION $REGISTRY_PATH/$APP_NAME:$APP_VERSION-${GITHUB_SHA::7}
        docker tag $APP_NAME:$APP_VERSION $REGISTRY_PATH/$APP_NAME:latest
        docker push $REGISTRY_PATH/$APP_NAME:$APP_VERSION-${GITHUB_SHA::7}
        docker push $REGISTRY_PATH/$APP_NAME:latest

  # TODO: Fix it later. Uneeded but fun functionality
  # package-chart:
  #   runs-on: ubuntu-latest
  #   needs: build-app
  #   permissions:
  #     contents: 'read'
  #     id-token: 'write'
  #   steps:
  #   - name: Checkout repository
  #     uses: actions/checkout@v3
  #   - name: 'Authenticate to Google Cloud'
  #     id: 'auth'
  #     uses: 'google-github-actions/auth@v0'
  #     with:
  #       workload_identity_provider: ${{ secrets.GCLOUD_WORKLOAD_IDENTITY_PROVIDER }}
  #       service_account: ${{ secrets.GCLOUD_SVC_ACCOUNT }}
  #       token_format: 'access_token'
  #   - name: Package helm chart
  #     run: helm package ./helm
  #   - name: Configure gcloud
  #     run: gcloud auth configure-docker ${{ env.REGISTRY_LOCALE }}
  #   - name: Pushing Helm package to Artefact Registry
  #     run: |
  #       helm version
  #       helm push {{ env.APP_NAME }}-0.1.0.tgz "oci://{{ env.REGISTRY_PATH }}" --kube-token ${{ steps.auth.outputs.access_token }} --debug

  deploy:
    runs-on: ubuntu-latest
    needs: build-image
    permissions:
      contents: 'read'
      id-token: 'write'
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
    - name: 'Authenticate to Google Cloud'
      id: 'auth'
      uses: 'google-github-actions/auth@v0'
      with:
        workload_identity_provider: ${{ secrets.GCLOUD_WORKLOAD_IDENTITY_PROVIDER }}
        service_account: ${{ secrets.GCLOUD_SVC_ACCOUNT }}
    - name: Deploy to GKE
      run: |
        gcloud container clusters get-credentials $GKE_CLUSTER --zone $GKE_ZONE --project $GKE_PROJECT
        helm upgrade $GKE_PROJECT ./helm --install \
          --namespace mower-planner --create-namespace \
          --set weatherapi.token=${{ secrets.WEATHER_API_TOKEN }},weatherapi.lat=${{ secrets.WEATHER_API_LAT }},weatherapi.lng=${{ secrets.WEATHER_API_LNG }} \
          --set mower.app.key=${{ secrets.MOW_APP_KEY }},mower.app.secret=${{ secrets.MOW_APP_SECRET }},mower.user=${{ secrets.MOW_USER }},mower.password=${{ secrets.MOW_PASS }} \
          --set mower.mowerid=${{ secrets.MOW_MOWER_ID }} \
          --wait
